/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * EduGen ClassLink API specification
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  Attendance,
  AuthResponse,
  AwardBadgeBody,
  Badge,
  CreateLessonBody,
  CreateQuizBody,
  ErrorResponse,
  HealthStatus,
  Lesson,
  LessonAccess,
  ListAttendanceParams,
  ListBadgesParams,
  ListLessonsParams,
  ListProgressParams,
  ListQuizzesParams,
  ListTopicsParams,
  ListUsersParams,
  LoginBody,
  MarkAttendanceBody,
  MessageResponse,
  Progress,
  Quiz,
  QuizResult,
  RegisterBody,
  StudentDashboard,
  SubmitQuizBody,
  TeacherDashboard,
  Topic,
  UpdateLessonBody,
  UpdateProgressBody,
  UpdateUserBody,
  User,
} from "./api.schemas";

import { customFetch } from "../custom-fetch";
import type { ErrorType, BodyType } from "../custom-fetch";

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Health check
 */
export const getHealthCheckUrl = () => {
  return `/api/healthz`;
};

export const healthCheck = async (
  options?: RequestInit,
): Promise<HealthStatus> => {
  return customFetch<HealthStatus>(getHealthCheckUrl(), {
    ...options,
    method: "GET",
  });
};

export const getHealthCheckQueryKey = () => {
  return [`/api/healthz`] as const;
};

export const getHealthCheckQueryOptions = <
  TData = Awaited<ReturnType<typeof healthCheck>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof healthCheck>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getHealthCheckQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof healthCheck>>> = ({
    signal,
  }) => healthCheck({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof healthCheck>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type HealthCheckQueryResult = NonNullable<
  Awaited<ReturnType<typeof healthCheck>>
>;
export type HealthCheckQueryError = ErrorType<unknown>;

/**
 * @summary Health check
 */

export function useHealthCheck<
  TData = Awaited<ReturnType<typeof healthCheck>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof healthCheck>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getHealthCheckQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Register a new user
 */
export const getRegisterUrl = () => {
  return `/api/auth/register`;
};

export const register = async (
  registerBody: RegisterBody,
  options?: RequestInit,
): Promise<AuthResponse> => {
  return customFetch<AuthResponse>(getRegisterUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(registerBody),
  });
};

export const getRegisterMutationOptions = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof register>>,
    TError,
    { data: BodyType<RegisterBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof register>>,
  TError,
  { data: BodyType<RegisterBody> },
  TContext
> => {
  const mutationKey = ["register"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof register>>,
    { data: BodyType<RegisterBody> }
  > = (props) => {
    const { data } = props ?? {};

    return register(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RegisterMutationResult = NonNullable<
  Awaited<ReturnType<typeof register>>
>;
export type RegisterMutationBody = BodyType<RegisterBody>;
export type RegisterMutationError = ErrorType<ErrorResponse>;

/**
 * @summary Register a new user
 */
export const useRegister = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof register>>,
    TError,
    { data: BodyType<RegisterBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof register>>,
  TError,
  { data: BodyType<RegisterBody> },
  TContext
> => {
  return useMutation(getRegisterMutationOptions(options));
};

/**
 * @summary Login
 */
export const getLoginUrl = () => {
  return `/api/auth/login`;
};

export const login = async (
  loginBody: LoginBody,
  options?: RequestInit,
): Promise<AuthResponse> => {
  return customFetch<AuthResponse>(getLoginUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(loginBody),
  });
};

export const getLoginMutationOptions = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof login>>,
    TError,
    { data: BodyType<LoginBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof login>>,
  TError,
  { data: BodyType<LoginBody> },
  TContext
> => {
  const mutationKey = ["login"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof login>>,
    { data: BodyType<LoginBody> }
  > = (props) => {
    const { data } = props ?? {};

    return login(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type LoginMutationResult = NonNullable<
  Awaited<ReturnType<typeof login>>
>;
export type LoginMutationBody = BodyType<LoginBody>;
export type LoginMutationError = ErrorType<ErrorResponse>;

/**
 * @summary Login
 */
export const useLogin = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof login>>,
    TError,
    { data: BodyType<LoginBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof login>>,
  TError,
  { data: BodyType<LoginBody> },
  TContext
> => {
  return useMutation(getLoginMutationOptions(options));
};

/**
 * @summary Logout
 */
export const getLogoutUrl = () => {
  return `/api/auth/logout`;
};

export const logout = async (
  options?: RequestInit,
): Promise<MessageResponse> => {
  return customFetch<MessageResponse>(getLogoutUrl(), {
    ...options,
    method: "POST",
  });
};

export const getLogoutMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof logout>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof logout>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["logout"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof logout>>,
    void
  > = () => {
    return logout(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type LogoutMutationResult = NonNullable<
  Awaited<ReturnType<typeof logout>>
>;

export type LogoutMutationError = ErrorType<unknown>;

/**
 * @summary Logout
 */
export const useLogout = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof logout>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof logout>>,
  TError,
  void,
  TContext
> => {
  return useMutation(getLogoutMutationOptions(options));
};

/**
 * @summary Get current user
 */
export const getGetMeUrl = () => {
  return `/api/auth/me`;
};

export const getMe = async (options?: RequestInit): Promise<User> => {
  return customFetch<User>(getGetMeUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetMeQueryKey = () => {
  return [`/api/auth/me`] as const;
};

export const getGetMeQueryOptions = <
  TData = Awaited<ReturnType<typeof getMe>>,
  TError = ErrorType<ErrorResponse>,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetMeQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getMe>>> = ({
    signal,
  }) => getMe({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getMe>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetMeQueryResult = NonNullable<Awaited<ReturnType<typeof getMe>>>;
export type GetMeQueryError = ErrorType<ErrorResponse>;

/**
 * @summary Get current user
 */

export function useGetMe<
  TData = Awaited<ReturnType<typeof getMe>>,
  TError = ErrorType<ErrorResponse>,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetMeQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary List users (teacher sees their students)
 */
export const getListUsersUrl = (params?: ListUsersParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/users?${stringifiedParams}`
    : `/api/users`;
};

export const listUsers = async (
  params?: ListUsersParams,
  options?: RequestInit,
): Promise<User[]> => {
  return customFetch<User[]>(getListUsersUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getListUsersQueryKey = (params?: ListUsersParams) => {
  return [`/api/users`, ...(params ? [params] : [])] as const;
};

export const getListUsersQueryOptions = <
  TData = Awaited<ReturnType<typeof listUsers>>,
  TError = ErrorType<unknown>,
>(
  params?: ListUsersParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listUsers>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListUsersQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listUsers>>> = ({
    signal,
  }) => listUsers(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listUsers>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ListUsersQueryResult = NonNullable<
  Awaited<ReturnType<typeof listUsers>>
>;
export type ListUsersQueryError = ErrorType<unknown>;

/**
 * @summary List users (teacher sees their students)
 */

export function useListUsers<
  TData = Awaited<ReturnType<typeof listUsers>>,
  TError = ErrorType<unknown>,
>(
  params?: ListUsersParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listUsers>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getListUsersQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get a user
 */
export const getGetUserUrl = (id: number) => {
  return `/api/users/${id}`;
};

export const getUser = async (
  id: number,
  options?: RequestInit,
): Promise<User> => {
  return customFetch<User>(getGetUserUrl(id), {
    ...options,
    method: "GET",
  });
};

export const getGetUserQueryKey = (id: number) => {
  return [`/api/users/${id}`] as const;
};

export const getGetUserQueryOptions = <
  TData = Awaited<ReturnType<typeof getUser>>,
  TError = ErrorType<unknown>,
>(
  id: number,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof getUser>>, TError, TData>;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetUserQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getUser>>> = ({
    signal,
  }) => getUser(id, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof getUser>>, TError, TData> & {
    queryKey: QueryKey;
  };
};

export type GetUserQueryResult = NonNullable<
  Awaited<ReturnType<typeof getUser>>
>;
export type GetUserQueryError = ErrorType<unknown>;

/**
 * @summary Get a user
 */

export function useGetUser<
  TData = Awaited<ReturnType<typeof getUser>>,
  TError = ErrorType<unknown>,
>(
  id: number,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof getUser>>, TError, TData>;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetUserQueryOptions(id, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Update user profile
 */
export const getUpdateUserUrl = (id: number) => {
  return `/api/users/${id}`;
};

export const updateUser = async (
  id: number,
  updateUserBody: UpdateUserBody,
  options?: RequestInit,
): Promise<User> => {
  return customFetch<User>(getUpdateUserUrl(id), {
    ...options,
    method: "PATCH",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(updateUserBody),
  });
};

export const getUpdateUserMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateUser>>,
    TError,
    { id: number; data: BodyType<UpdateUserBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateUser>>,
  TError,
  { id: number; data: BodyType<UpdateUserBody> },
  TContext
> => {
  const mutationKey = ["updateUser"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateUser>>,
    { id: number; data: BodyType<UpdateUserBody> }
  > = (props) => {
    const { id, data } = props ?? {};

    return updateUser(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateUserMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateUser>>
>;
export type UpdateUserMutationBody = BodyType<UpdateUserBody>;
export type UpdateUserMutationError = ErrorType<unknown>;

/**
 * @summary Update user profile
 */
export const useUpdateUser = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateUser>>,
    TError,
    { id: number; data: BodyType<UpdateUserBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof updateUser>>,
  TError,
  { id: number; data: BodyType<UpdateUserBody> },
  TContext
> => {
  return useMutation(getUpdateUserMutationOptions(options));
};

/**
 * @summary List lessons
 */
export const getListLessonsUrl = (params?: ListLessonsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/lessons?${stringifiedParams}`
    : `/api/lessons`;
};

export const listLessons = async (
  params?: ListLessonsParams,
  options?: RequestInit,
): Promise<Lesson[]> => {
  return customFetch<Lesson[]>(getListLessonsUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getListLessonsQueryKey = (params?: ListLessonsParams) => {
  return [`/api/lessons`, ...(params ? [params] : [])] as const;
};

export const getListLessonsQueryOptions = <
  TData = Awaited<ReturnType<typeof listLessons>>,
  TError = ErrorType<unknown>,
>(
  params?: ListLessonsParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listLessons>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListLessonsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listLessons>>> = ({
    signal,
  }) => listLessons(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listLessons>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ListLessonsQueryResult = NonNullable<
  Awaited<ReturnType<typeof listLessons>>
>;
export type ListLessonsQueryError = ErrorType<unknown>;

/**
 * @summary List lessons
 */

export function useListLessons<
  TData = Awaited<ReturnType<typeof listLessons>>,
  TError = ErrorType<unknown>,
>(
  params?: ListLessonsParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listLessons>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getListLessonsQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Create a lesson
 */
export const getCreateLessonUrl = () => {
  return `/api/lessons`;
};

export const createLesson = async (
  createLessonBody: CreateLessonBody,
  options?: RequestInit,
): Promise<Lesson> => {
  return customFetch<Lesson>(getCreateLessonUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createLessonBody),
  });
};

export const getCreateLessonMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createLesson>>,
    TError,
    { data: BodyType<CreateLessonBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createLesson>>,
  TError,
  { data: BodyType<CreateLessonBody> },
  TContext
> => {
  const mutationKey = ["createLesson"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createLesson>>,
    { data: BodyType<CreateLessonBody> }
  > = (props) => {
    const { data } = props ?? {};

    return createLesson(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateLessonMutationResult = NonNullable<
  Awaited<ReturnType<typeof createLesson>>
>;
export type CreateLessonMutationBody = BodyType<CreateLessonBody>;
export type CreateLessonMutationError = ErrorType<unknown>;

/**
 * @summary Create a lesson
 */
export const useCreateLesson = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createLesson>>,
    TError,
    { data: BodyType<CreateLessonBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof createLesson>>,
  TError,
  { data: BodyType<CreateLessonBody> },
  TContext
> => {
  return useMutation(getCreateLessonMutationOptions(options));
};

/**
 * @summary Get a lesson
 */
export const getGetLessonUrl = (id: number) => {
  return `/api/lessons/${id}`;
};

export const getLesson = async (
  id: number,
  options?: RequestInit,
): Promise<Lesson> => {
  return customFetch<Lesson>(getGetLessonUrl(id), {
    ...options,
    method: "GET",
  });
};

export const getGetLessonQueryKey = (id: number) => {
  return [`/api/lessons/${id}`] as const;
};

export const getGetLessonQueryOptions = <
  TData = Awaited<ReturnType<typeof getLesson>>,
  TError = ErrorType<unknown>,
>(
  id: number,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getLesson>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetLessonQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getLesson>>> = ({
    signal,
  }) => getLesson(id, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof getLesson>>, TError, TData> & {
    queryKey: QueryKey;
  };
};

export type GetLessonQueryResult = NonNullable<
  Awaited<ReturnType<typeof getLesson>>
>;
export type GetLessonQueryError = ErrorType<unknown>;

/**
 * @summary Get a lesson
 */

export function useGetLesson<
  TData = Awaited<ReturnType<typeof getLesson>>,
  TError = ErrorType<unknown>,
>(
  id: number,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getLesson>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetLessonQueryOptions(id, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Update a lesson
 */
export const getUpdateLessonUrl = (id: number) => {
  return `/api/lessons/${id}`;
};

export const updateLesson = async (
  id: number,
  updateLessonBody: UpdateLessonBody,
  options?: RequestInit,
): Promise<Lesson> => {
  return customFetch<Lesson>(getUpdateLessonUrl(id), {
    ...options,
    method: "PATCH",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(updateLessonBody),
  });
};

export const getUpdateLessonMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateLesson>>,
    TError,
    { id: number; data: BodyType<UpdateLessonBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateLesson>>,
  TError,
  { id: number; data: BodyType<UpdateLessonBody> },
  TContext
> => {
  const mutationKey = ["updateLesson"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateLesson>>,
    { id: number; data: BodyType<UpdateLessonBody> }
  > = (props) => {
    const { id, data } = props ?? {};

    return updateLesson(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateLessonMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateLesson>>
>;
export type UpdateLessonMutationBody = BodyType<UpdateLessonBody>;
export type UpdateLessonMutationError = ErrorType<unknown>;

/**
 * @summary Update a lesson
 */
export const useUpdateLesson = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateLesson>>,
    TError,
    { id: number; data: BodyType<UpdateLessonBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof updateLesson>>,
  TError,
  { id: number; data: BodyType<UpdateLessonBody> },
  TContext
> => {
  return useMutation(getUpdateLessonMutationOptions(options));
};

/**
 * @summary Delete a lesson
 */
export const getDeleteLessonUrl = (id: number) => {
  return `/api/lessons/${id}`;
};

export const deleteLesson = async (
  id: number,
  options?: RequestInit,
): Promise<MessageResponse> => {
  return customFetch<MessageResponse>(getDeleteLessonUrl(id), {
    ...options,
    method: "DELETE",
  });
};

export const getDeleteLessonMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteLesson>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteLesson>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ["deleteLesson"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteLesson>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return deleteLesson(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteLessonMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteLesson>>
>;

export type DeleteLessonMutationError = ErrorType<unknown>;

/**
 * @summary Delete a lesson
 */
export const useDeleteLesson = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteLesson>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof deleteLesson>>,
  TError,
  { id: number },
  TContext
> => {
  return useMutation(getDeleteLessonMutationOptions(options));
};

/**
 * @summary Publish a lesson to students
 */
export const getPublishLessonUrl = (id: number) => {
  return `/api/lessons/${id}/publish`;
};

export const publishLesson = async (
  id: number,
  options?: RequestInit,
): Promise<Lesson> => {
  return customFetch<Lesson>(getPublishLessonUrl(id), {
    ...options,
    method: "POST",
  });
};

export const getPublishLessonMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof publishLesson>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof publishLesson>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ["publishLesson"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof publishLesson>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return publishLesson(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PublishLessonMutationResult = NonNullable<
  Awaited<ReturnType<typeof publishLesson>>
>;

export type PublishLessonMutationError = ErrorType<unknown>;

/**
 * @summary Publish a lesson to students
 */
export const usePublishLesson = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof publishLesson>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof publishLesson>>,
  TError,
  { id: number },
  TContext
> => {
  return useMutation(getPublishLessonMutationOptions(options));
};

/**
 * @summary Get which students have accessed this lesson
 */
export const getGetLessonAccessUrl = (id: number) => {
  return `/api/lessons/${id}/access`;
};

export const getLessonAccess = async (
  id: number,
  options?: RequestInit,
): Promise<LessonAccess[]> => {
  return customFetch<LessonAccess[]>(getGetLessonAccessUrl(id), {
    ...options,
    method: "GET",
  });
};

export const getGetLessonAccessQueryKey = (id: number) => {
  return [`/api/lessons/${id}/access`] as const;
};

export const getGetLessonAccessQueryOptions = <
  TData = Awaited<ReturnType<typeof getLessonAccess>>,
  TError = ErrorType<unknown>,
>(
  id: number,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getLessonAccess>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetLessonAccessQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getLessonAccess>>> = ({
    signal,
  }) => getLessonAccess(id, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getLessonAccess>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetLessonAccessQueryResult = NonNullable<
  Awaited<ReturnType<typeof getLessonAccess>>
>;
export type GetLessonAccessQueryError = ErrorType<unknown>;

/**
 * @summary Get which students have accessed this lesson
 */

export function useGetLessonAccess<
  TData = Awaited<ReturnType<typeof getLessonAccess>>,
  TError = ErrorType<unknown>,
>(
  id: number,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getLessonAccess>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetLessonAccessQueryOptions(id, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Mark a lesson as viewed by student
 */
export const getMarkLessonViewedUrl = (id: number) => {
  return `/api/lessons/${id}/viewed`;
};

export const markLessonViewed = async (
  id: number,
  options?: RequestInit,
): Promise<MessageResponse> => {
  return customFetch<MessageResponse>(getMarkLessonViewedUrl(id), {
    ...options,
    method: "POST",
  });
};

export const getMarkLessonViewedMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof markLessonViewed>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof markLessonViewed>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ["markLessonViewed"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof markLessonViewed>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return markLessonViewed(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type MarkLessonViewedMutationResult = NonNullable<
  Awaited<ReturnType<typeof markLessonViewed>>
>;

export type MarkLessonViewedMutationError = ErrorType<unknown>;

/**
 * @summary Mark a lesson as viewed by student
 */
export const useMarkLessonViewed = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof markLessonViewed>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof markLessonViewed>>,
  TError,
  { id: number },
  TContext
> => {
  return useMutation(getMarkLessonViewedMutationOptions(options));
};

/**
 * @summary List attendance records
 */
export const getListAttendanceUrl = (params?: ListAttendanceParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/attendance?${stringifiedParams}`
    : `/api/attendance`;
};

export const listAttendance = async (
  params?: ListAttendanceParams,
  options?: RequestInit,
): Promise<Attendance[]> => {
  return customFetch<Attendance[]>(getListAttendanceUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getListAttendanceQueryKey = (params?: ListAttendanceParams) => {
  return [`/api/attendance`, ...(params ? [params] : [])] as const;
};

export const getListAttendanceQueryOptions = <
  TData = Awaited<ReturnType<typeof listAttendance>>,
  TError = ErrorType<unknown>,
>(
  params?: ListAttendanceParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listAttendance>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListAttendanceQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listAttendance>>> = ({
    signal,
  }) => listAttendance(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listAttendance>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ListAttendanceQueryResult = NonNullable<
  Awaited<ReturnType<typeof listAttendance>>
>;
export type ListAttendanceQueryError = ErrorType<unknown>;

/**
 * @summary List attendance records
 */

export function useListAttendance<
  TData = Awaited<ReturnType<typeof listAttendance>>,
  TError = ErrorType<unknown>,
>(
  params?: ListAttendanceParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listAttendance>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getListAttendanceQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Mark attendance for students
 */
export const getMarkAttendanceUrl = () => {
  return `/api/attendance`;
};

export const markAttendance = async (
  markAttendanceBody: MarkAttendanceBody,
  options?: RequestInit,
): Promise<Attendance[]> => {
  return customFetch<Attendance[]>(getMarkAttendanceUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(markAttendanceBody),
  });
};

export const getMarkAttendanceMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof markAttendance>>,
    TError,
    { data: BodyType<MarkAttendanceBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof markAttendance>>,
  TError,
  { data: BodyType<MarkAttendanceBody> },
  TContext
> => {
  const mutationKey = ["markAttendance"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof markAttendance>>,
    { data: BodyType<MarkAttendanceBody> }
  > = (props) => {
    const { data } = props ?? {};

    return markAttendance(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type MarkAttendanceMutationResult = NonNullable<
  Awaited<ReturnType<typeof markAttendance>>
>;
export type MarkAttendanceMutationBody = BodyType<MarkAttendanceBody>;
export type MarkAttendanceMutationError = ErrorType<unknown>;

/**
 * @summary Mark attendance for students
 */
export const useMarkAttendance = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof markAttendance>>,
    TError,
    { data: BodyType<MarkAttendanceBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof markAttendance>>,
  TError,
  { data: BodyType<MarkAttendanceBody> },
  TContext
> => {
  return useMutation(getMarkAttendanceMutationOptions(options));
};

/**
 * @summary List student progress
 */
export const getListProgressUrl = (params?: ListProgressParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/progress?${stringifiedParams}`
    : `/api/progress`;
};

export const listProgress = async (
  params?: ListProgressParams,
  options?: RequestInit,
): Promise<Progress[]> => {
  return customFetch<Progress[]>(getListProgressUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getListProgressQueryKey = (params?: ListProgressParams) => {
  return [`/api/progress`, ...(params ? [params] : [])] as const;
};

export const getListProgressQueryOptions = <
  TData = Awaited<ReturnType<typeof listProgress>>,
  TError = ErrorType<unknown>,
>(
  params?: ListProgressParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listProgress>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListProgressQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listProgress>>> = ({
    signal,
  }) => listProgress(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listProgress>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ListProgressQueryResult = NonNullable<
  Awaited<ReturnType<typeof listProgress>>
>;
export type ListProgressQueryError = ErrorType<unknown>;

/**
 * @summary List student progress
 */

export function useListProgress<
  TData = Awaited<ReturnType<typeof listProgress>>,
  TError = ErrorType<unknown>,
>(
  params?: ListProgressParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listProgress>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getListProgressQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Update student progress
 */
export const getUpdateProgressUrl = () => {
  return `/api/progress`;
};

export const updateProgress = async (
  updateProgressBody: UpdateProgressBody,
  options?: RequestInit,
): Promise<Progress> => {
  return customFetch<Progress>(getUpdateProgressUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(updateProgressBody),
  });
};

export const getUpdateProgressMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateProgress>>,
    TError,
    { data: BodyType<UpdateProgressBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateProgress>>,
  TError,
  { data: BodyType<UpdateProgressBody> },
  TContext
> => {
  const mutationKey = ["updateProgress"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateProgress>>,
    { data: BodyType<UpdateProgressBody> }
  > = (props) => {
    const { data } = props ?? {};

    return updateProgress(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateProgressMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateProgress>>
>;
export type UpdateProgressMutationBody = BodyType<UpdateProgressBody>;
export type UpdateProgressMutationError = ErrorType<unknown>;

/**
 * @summary Update student progress
 */
export const useUpdateProgress = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateProgress>>,
    TError,
    { data: BodyType<UpdateProgressBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof updateProgress>>,
  TError,
  { data: BodyType<UpdateProgressBody> },
  TContext
> => {
  return useMutation(getUpdateProgressMutationOptions(options));
};

/**
 * @summary List badges for a student
 */
export const getListBadgesUrl = (params?: ListBadgesParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/badges?${stringifiedParams}`
    : `/api/badges`;
};

export const listBadges = async (
  params?: ListBadgesParams,
  options?: RequestInit,
): Promise<Badge[]> => {
  return customFetch<Badge[]>(getListBadgesUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getListBadgesQueryKey = (params?: ListBadgesParams) => {
  return [`/api/badges`, ...(params ? [params] : [])] as const;
};

export const getListBadgesQueryOptions = <
  TData = Awaited<ReturnType<typeof listBadges>>,
  TError = ErrorType<unknown>,
>(
  params?: ListBadgesParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listBadges>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListBadgesQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listBadges>>> = ({
    signal,
  }) => listBadges(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listBadges>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ListBadgesQueryResult = NonNullable<
  Awaited<ReturnType<typeof listBadges>>
>;
export type ListBadgesQueryError = ErrorType<unknown>;

/**
 * @summary List badges for a student
 */

export function useListBadges<
  TData = Awaited<ReturnType<typeof listBadges>>,
  TError = ErrorType<unknown>,
>(
  params?: ListBadgesParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listBadges>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getListBadgesQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Award a badge to a student
 */
export const getAwardBadgeUrl = () => {
  return `/api/badges`;
};

export const awardBadge = async (
  awardBadgeBody: AwardBadgeBody,
  options?: RequestInit,
): Promise<Badge> => {
  return customFetch<Badge>(getAwardBadgeUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(awardBadgeBody),
  });
};

export const getAwardBadgeMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof awardBadge>>,
    TError,
    { data: BodyType<AwardBadgeBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof awardBadge>>,
  TError,
  { data: BodyType<AwardBadgeBody> },
  TContext
> => {
  const mutationKey = ["awardBadge"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof awardBadge>>,
    { data: BodyType<AwardBadgeBody> }
  > = (props) => {
    const { data } = props ?? {};

    return awardBadge(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AwardBadgeMutationResult = NonNullable<
  Awaited<ReturnType<typeof awardBadge>>
>;
export type AwardBadgeMutationBody = BodyType<AwardBadgeBody>;
export type AwardBadgeMutationError = ErrorType<unknown>;

/**
 * @summary Award a badge to a student
 */
export const useAwardBadge = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof awardBadge>>,
    TError,
    { data: BodyType<AwardBadgeBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof awardBadge>>,
  TError,
  { data: BodyType<AwardBadgeBody> },
  TContext
> => {
  return useMutation(getAwardBadgeMutationOptions(options));
};

/**
 * @summary List quizzes
 */
export const getListQuizzesUrl = (params?: ListQuizzesParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/quizzes?${stringifiedParams}`
    : `/api/quizzes`;
};

export const listQuizzes = async (
  params?: ListQuizzesParams,
  options?: RequestInit,
): Promise<Quiz[]> => {
  return customFetch<Quiz[]>(getListQuizzesUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getListQuizzesQueryKey = (params?: ListQuizzesParams) => {
  return [`/api/quizzes`, ...(params ? [params] : [])] as const;
};

export const getListQuizzesQueryOptions = <
  TData = Awaited<ReturnType<typeof listQuizzes>>,
  TError = ErrorType<unknown>,
>(
  params?: ListQuizzesParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listQuizzes>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListQuizzesQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listQuizzes>>> = ({
    signal,
  }) => listQuizzes(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listQuizzes>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ListQuizzesQueryResult = NonNullable<
  Awaited<ReturnType<typeof listQuizzes>>
>;
export type ListQuizzesQueryError = ErrorType<unknown>;

/**
 * @summary List quizzes
 */

export function useListQuizzes<
  TData = Awaited<ReturnType<typeof listQuizzes>>,
  TError = ErrorType<unknown>,
>(
  params?: ListQuizzesParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listQuizzes>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getListQuizzesQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Create a quiz
 */
export const getCreateQuizUrl = () => {
  return `/api/quizzes`;
};

export const createQuiz = async (
  createQuizBody: CreateQuizBody,
  options?: RequestInit,
): Promise<Quiz> => {
  return customFetch<Quiz>(getCreateQuizUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createQuizBody),
  });
};

export const getCreateQuizMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createQuiz>>,
    TError,
    { data: BodyType<CreateQuizBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createQuiz>>,
  TError,
  { data: BodyType<CreateQuizBody> },
  TContext
> => {
  const mutationKey = ["createQuiz"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createQuiz>>,
    { data: BodyType<CreateQuizBody> }
  > = (props) => {
    const { data } = props ?? {};

    return createQuiz(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateQuizMutationResult = NonNullable<
  Awaited<ReturnType<typeof createQuiz>>
>;
export type CreateQuizMutationBody = BodyType<CreateQuizBody>;
export type CreateQuizMutationError = ErrorType<unknown>;

/**
 * @summary Create a quiz
 */
export const useCreateQuiz = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createQuiz>>,
    TError,
    { data: BodyType<CreateQuizBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof createQuiz>>,
  TError,
  { data: BodyType<CreateQuizBody> },
  TContext
> => {
  return useMutation(getCreateQuizMutationOptions(options));
};

/**
 * @summary Submit quiz answers
 */
export const getSubmitQuizUrl = (id: number) => {
  return `/api/quizzes/${id}/submit`;
};

export const submitQuiz = async (
  id: number,
  submitQuizBody: SubmitQuizBody,
  options?: RequestInit,
): Promise<QuizResult> => {
  return customFetch<QuizResult>(getSubmitQuizUrl(id), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(submitQuizBody),
  });
};

export const getSubmitQuizMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof submitQuiz>>,
    TError,
    { id: number; data: BodyType<SubmitQuizBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof submitQuiz>>,
  TError,
  { id: number; data: BodyType<SubmitQuizBody> },
  TContext
> => {
  const mutationKey = ["submitQuiz"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof submitQuiz>>,
    { id: number; data: BodyType<SubmitQuizBody> }
  > = (props) => {
    const { id, data } = props ?? {};

    return submitQuiz(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type SubmitQuizMutationResult = NonNullable<
  Awaited<ReturnType<typeof submitQuiz>>
>;
export type SubmitQuizMutationBody = BodyType<SubmitQuizBody>;
export type SubmitQuizMutationError = ErrorType<unknown>;

/**
 * @summary Submit quiz answers
 */
export const useSubmitQuiz = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof submitQuiz>>,
    TError,
    { id: number; data: BodyType<SubmitQuizBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof submitQuiz>>,
  TError,
  { id: number; data: BodyType<SubmitQuizBody> },
  TContext
> => {
  return useMutation(getSubmitQuizMutationOptions(options));
};

/**
 * @summary List topics from the preloaded topic library
 */
export const getListTopicsUrl = (params?: ListTopicsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/topics?${stringifiedParams}`
    : `/api/topics`;
};

export const listTopics = async (
  params?: ListTopicsParams,
  options?: RequestInit,
): Promise<Topic[]> => {
  return customFetch<Topic[]>(getListTopicsUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getListTopicsQueryKey = (params?: ListTopicsParams) => {
  return [`/api/topics`, ...(params ? [params] : [])] as const;
};

export const getListTopicsQueryOptions = <
  TData = Awaited<ReturnType<typeof listTopics>>,
  TError = ErrorType<unknown>,
>(
  params?: ListTopicsParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listTopics>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListTopicsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listTopics>>> = ({
    signal,
  }) => listTopics(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listTopics>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ListTopicsQueryResult = NonNullable<
  Awaited<ReturnType<typeof listTopics>>
>;
export type ListTopicsQueryError = ErrorType<unknown>;

/**
 * @summary List topics from the preloaded topic library
 */

export function useListTopics<
  TData = Awaited<ReturnType<typeof listTopics>>,
  TError = ErrorType<unknown>,
>(
  params?: ListTopicsParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listTopics>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getListTopicsQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get teacher dashboard summary
 */
export const getGetTeacherDashboardUrl = () => {
  return `/api/dashboard/teacher`;
};

export const getTeacherDashboard = async (
  options?: RequestInit,
): Promise<TeacherDashboard> => {
  return customFetch<TeacherDashboard>(getGetTeacherDashboardUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetTeacherDashboardQueryKey = () => {
  return [`/api/dashboard/teacher`] as const;
};

export const getGetTeacherDashboardQueryOptions = <
  TData = Awaited<ReturnType<typeof getTeacherDashboard>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getTeacherDashboard>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetTeacherDashboardQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getTeacherDashboard>>
  > = ({ signal }) => getTeacherDashboard({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getTeacherDashboard>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetTeacherDashboardQueryResult = NonNullable<
  Awaited<ReturnType<typeof getTeacherDashboard>>
>;
export type GetTeacherDashboardQueryError = ErrorType<unknown>;

/**
 * @summary Get teacher dashboard summary
 */

export function useGetTeacherDashboard<
  TData = Awaited<ReturnType<typeof getTeacherDashboard>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getTeacherDashboard>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetTeacherDashboardQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get student dashboard summary
 */
export const getGetStudentDashboardUrl = () => {
  return `/api/dashboard/student`;
};

export const getStudentDashboard = async (
  options?: RequestInit,
): Promise<StudentDashboard> => {
  return customFetch<StudentDashboard>(getGetStudentDashboardUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetStudentDashboardQueryKey = () => {
  return [`/api/dashboard/student`] as const;
};

export const getGetStudentDashboardQueryOptions = <
  TData = Awaited<ReturnType<typeof getStudentDashboard>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getStudentDashboard>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetStudentDashboardQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getStudentDashboard>>
  > = ({ signal }) => getStudentDashboard({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getStudentDashboard>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetStudentDashboardQueryResult = NonNullable<
  Awaited<ReturnType<typeof getStudentDashboard>>
>;
export type GetStudentDashboardQueryError = ErrorType<unknown>;

/**
 * @summary Get student dashboard summary
 */

export function useGetStudentDashboard<
  TData = Awaited<ReturnType<typeof getStudentDashboard>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getStudentDashboard>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetStudentDashboardQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}
