/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * EduGen ClassLink API specification
 * OpenAPI spec version: 0.1.0
 */
export interface HealthStatus {
  status: string;
}

export interface ErrorResponse {
  error: string;
  message?: string;
}

export interface MessageResponse {
  message: string;
}

export type UserRole = (typeof UserRole)[keyof typeof UserRole];

export const UserRole = {
  teacher: "teacher",
  student: "student",
} as const;

export interface User {
  id: number;
  name: string;
  email: string;
  role: UserRole;
  grade?: string;
  division?: string;
  board?: string;
  subject?: string;
  school?: string;
  avatarUrl?: string;
  teacherId?: number;
  aiApiKey?: string;
  createdAt: string;
}

export interface AuthResponse {
  user: User;
  message: string;
}

export type RegisterBodyRole =
  (typeof RegisterBodyRole)[keyof typeof RegisterBodyRole];

export const RegisterBodyRole = {
  teacher: "teacher",
  student: "student",
} as const;

export type RegisterBodyBoard =
  (typeof RegisterBodyBoard)[keyof typeof RegisterBodyBoard];

export const RegisterBodyBoard = {
  IGCSE: "IGCSE",
  CBSE: "CBSE",
  IB: "IB",
  ICSE: "ICSE",
  STATE: "STATE",
} as const;

export interface RegisterBody {
  name: string;
  email: string;
  password: string;
  role: RegisterBodyRole;
  grade?: string;
  division?: string;
  board?: RegisterBodyBoard;
  subject?: string;
  school?: string;
  teacherCode?: string;
}

export interface LoginBody {
  email: string;
  password: string;
}

export interface UpdateUserBody {
  name?: string;
  grade?: string;
  division?: string;
  board?: string;
  subject?: string;
  school?: string;
  avatarUrl?: string;
  aiApiKey?: string;
}

export interface Lesson {
  id: number;
  teacherId: number;
  title: string;
  subject: string;
  grade: string;
  division?: string;
  board?: string;
  topic: string;
  description?: string;
  content?: string;
  videoUrl?: string;
  resourceUrls?: string[];
  published: boolean;
  publishedAt?: string;
  lessonDate?: string;
  createdAt: string;
  teacher?: User;
  accessCount?: number;
  totalStudents?: number;
}

export interface CreateLessonBody {
  title: string;
  subject: string;
  grade: string;
  division?: string;
  board?: string;
  topic: string;
  description?: string;
  content?: string;
  videoUrl?: string;
  resourceUrls?: string[];
  lessonDate?: string;
}

export interface UpdateLessonBody {
  title?: string;
  subject?: string;
  grade?: string;
  division?: string;
  board?: string;
  topic?: string;
  description?: string;
  content?: string;
  videoUrl?: string;
  resourceUrls?: string[];
  lessonDate?: string;
  published?: boolean;
}

export interface LessonAccess {
  studentId: number;
  studentName: string;
  accessedAt?: string;
  viewed: boolean;
}

export type AttendanceStatus =
  (typeof AttendanceStatus)[keyof typeof AttendanceStatus];

export const AttendanceStatus = {
  present: "present",
  absent: "absent",
  late: "late",
} as const;

export interface Attendance {
  id: number;
  studentId: number;
  teacherId: number;
  date: string;
  status: AttendanceStatus;
  student?: User;
}

export type MarkAttendanceBodyRecordsItemStatus =
  (typeof MarkAttendanceBodyRecordsItemStatus)[keyof typeof MarkAttendanceBodyRecordsItemStatus];

export const MarkAttendanceBodyRecordsItemStatus = {
  present: "present",
  absent: "absent",
  late: "late",
} as const;

export type MarkAttendanceBodyRecordsItem = {
  studentId: number;
  status: MarkAttendanceBodyRecordsItemStatus;
};

export interface MarkAttendanceBody {
  date: string;
  records: MarkAttendanceBodyRecordsItem[];
}

export interface Progress {
  id: number;
  studentId: number;
  subject: string;
  topic?: string;
  score: number;
  gamesPlayed?: number;
  lessonsCompleted?: number;
  quizzesCompleted?: number;
  updatedAt?: string;
}

export interface UpdateProgressBody {
  subject: string;
  topic?: string;
  score?: number;
  gamesPlayed?: number;
  lessonsCompleted?: number;
  quizzesCompleted?: number;
}

export interface Badge {
  id: number;
  studentId: number;
  name: string;
  description?: string;
  icon: string;
  category?: string;
  awardedAt: string;
}

export interface AwardBadgeBody {
  studentId: number;
  name: string;
  description?: string;
  icon: string;
  category?: string;
}

export interface QuizQuestion {
  id: number;
  question: string;
  options: string[];
  correctIndex: number;
  explanation?: string;
}

export interface Quiz {
  id: number;
  lessonId?: number;
  teacherId?: number;
  title: string;
  subject: string;
  grade: string;
  topic: string;
  questions: QuizQuestion[];
  timeLimit?: number;
  createdAt: string;
}

export interface CreateQuizBody {
  lessonId?: number;
  title: string;
  subject: string;
  grade: string;
  topic: string;
  questions: QuizQuestion[];
  timeLimit?: number;
}

export interface SubmitQuizBody {
  answers: number[];
}

export type QuizResultFeedbackItem = {
  questionId: number;
  correct: boolean;
  explanation?: string;
};

export interface QuizResult {
  score: number;
  correct: number;
  total: number;
  passed: boolean;
  feedback?: QuizResultFeedbackItem[];
}

export interface Topic {
  id: number;
  subject: string;
  grade: string;
  title: string;
  description?: string;
  board?: string;
  keywords?: string[];
  gameType?: string;
  difficulty?: string;
}

export type TeacherDashboardSubjectBreakdownItem = {
  subject: string;
  count: number;
};

export interface TeacherDashboard {
  totalStudents: number;
  totalLessons: number;
  publishedLessons: number;
  todayAbsent: number;
  lessonAccessRate: number;
  recentLessons: Lesson[];
  attendanceToday: Attendance[];
  subjectBreakdown: TeacherDashboardSubjectBreakdownItem[];
}

export interface StudentDashboard {
  missedLessons: Lesson[];
  recentLessons: Lesson[];
  badges: Badge[];
  progress: Progress[];
  totalBadges: number;
  overallScore: number;
  streak: number;
  recommendedTopics: Topic[];
}

export type ListUsersParams = {
  role?: ListUsersRole;
  grade?: string;
  division?: string;
};

export type ListUsersRole = (typeof ListUsersRole)[keyof typeof ListUsersRole];

export const ListUsersRole = {
  teacher: "teacher",
  student: "student",
} as const;

export type ListLessonsParams = {
  grade?: string;
  subject?: string;
  board?: string;
  published?: boolean;
  teacherId?: number;
};

export type ListAttendanceParams = {
  date?: string;
  grade?: string;
  division?: string;
  studentId?: number;
};

export type ListProgressParams = {
  studentId?: number;
  subject?: string;
};

export type ListBadgesParams = {
  studentId?: number;
};

export type ListQuizzesParams = {
  lessonId?: number;
  grade?: string;
  subject?: string;
};

export type ListTopicsParams = {
  grade?: string;
  subject?: string;
  board?: string;
  search?: string;
};
